### ISSUE TITLE
Failing tests on bleed rakudo

### ISSUE THREAD

**Issue by AlexDaniel** [p6-css/CSS-Module-p6#10]
Example output: https://gist.github.com/Whateverable/0aef8e252affaf8ebc772c27af77c500

It was bisected to this rakudo commit: https://github.com/rakudo/rakudo/commit/1599873d1420fd5c06a10f8b134213866cbfd87e
So quite possibly it is actually related to this nqp commit: https://github.com/perl6/nqp/commit/f34562f5fb5bcf48dbf31c390ef57627706b9b66

Note that it works just fine with rakudo [1599873d1420^](https://gist.github.com/Whateverable/1f35ed3fe1d54403226277855fbe2a69).

I can't really tell if it is some problem with rakudo or if this module (or one of its dependencies) is doing something wrong.

**Comment by AlexDaniel** [comment]
Backlink: [RT #131919](https://rt.perl.org/Ticket/Display.html?id=131919#txn-1483009).

**Comment by dwarring** [comment]
Just to confirm. Getting failure with rakudo.2017.08 after reverting https://github.com/perl6/nqp/commit/d4d77b66c46c57de800b147df61fe486b4486acd

Ungolfed:
```
use CSS::Module::CSS3;
use CSS::Module::CSS3::Actions;
my CSS::Module::CSS3::Actions $actions .= new;
my $css = '@font-face { font-family: MainText; src: url(gentium.eot); /* for use with older user agents */ src: local(\'Gentium\'), url(gentium.ttf) format(\'truetype\');  /* Overrides src definition */ }';

CSS::Module::CSS3.parse($css, :$actions, :rule<at-rule>);
say $actions.warnings>>.message;
# [extra terms following 'src' declaration: ('Gentium') , url (gentium.ttf) format ('truetype') - dropped]
```

**Comment by dwarring** [comment]
Slightly golfed to the the following program:
```
use CSS::Module::CSS3::Fonts::AtFontFace;
say CSS::Module::CSS3::Fonts::AtFontFace.parse('{  src: local(\'Gentium\') }', :rule<declarations> )
```
which normally produces:
```
use CSS::Module::CSS3::Fonts::AtFontFace;
say CSS::Module::CSS3::Fonts::AtFontFace.parse('{  src: local(\'Gentium\') }', :rule<declarations> )
```

But after reverting https://github.com/perl6/nqp/commit/d4d77b66c46c57de800b147df61fe486b4486acd
```
use CSS::Module::CSS3::Fonts::AtFontFace;
say CSS::Module::CSS3::Fonts::AtFontFace.parse('{  src: local(\'Gentium\') }', :rule<declarations> )
```

**Comment by dwarring** [comment]
Further golfed, and isolated from CSS::Module, as added to https://rt.perl.org/Ticket/Display.html?id=131919:

```
grammar Tst {
    rule local {:i('local')'(' [ \'<ident>\' ] ')'}
    rule declaration-list { <test-prop> * }
    rule declarations {
        '{' <declaration-list> '}'
    }
    rule test-prop { (src) ':'  <local> +% ',' }
    }
say Tst.parse('{  src: local(\'Gentium\') }', :rule<declarations> )
```

**Comment by AlexDaniel** [comment]
I'm not entirely sure why the fix is needed? On all v6.c releases the snippet you provided works OK. 
Commits of interest are:
* (2017-08-19) https://github.com/rakudo/rakudo/commit/c5cb74abebda54a6abb5f6dfc3a681e95a7dbe36
* (2017-08-20) https://github.com/rakudo/rakudo/commit/2545e6d656ee97b23f09f508bb47f65be679507e

Some output: https://gist.github.com/AlexDaniel/10198eaebb128e03066058d3b0d70ad0

**Comment by AlexDaniel** [comment]
In other words, it was broken in Aug 2017 and I opened this ticket, but then it was fixed a few days later. No?
